class Signal(object):
    ASK_LED = "AL"
    ASK_LED_SYNC = "ALS"
    RESPONSE_LED = "RL"
    RES_DOWNLOAD_LED = "RDL"
    RES_EXIST_LED = "REL"
    DOWNLOAD_LED = "DL"
    DOWNLOAD_DONE_LED = "DDL"

    BRIGHTNESS = "B"
    SPEED = "S"
    FILTER = "F"
    EMERGENCY = "E"
    THRESHOLD_LEVEL = "TL"
    THRESHOLD_ENABLE = "TE"


    RES = "RES"
    CONNECTED = "CONNECTED"

    READ_BYTE_SEPARATE = "!S!"